name: build_container
author: itstimetoforget
description: build_container

inputs:
  push:
    required: false
    default: false
  load:
    required: false
    default: false
  tags:
    required: false
    default: ""
    description: "additional tags"

  token:
    required: true
    description: "Github-Token"

outputs:
  docker-image-tag:
    value: ${{ steps.meta.outputs.tags }}
    description: "docker tag"




runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@5b7b28b1cc417bbd34cd8c225a957c9ce9adf7f2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@032a4b3bda1b716928481836ac5bfe36e1feaad6
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          ${{ inputs.tags }}
          type=ref,event=branch
          type=sha

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
      with:
        context: .
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: actionfiles/aquafier-ts/dockerfile/Dockerfile