name: build_container
author: itstimetoforget
description: build_container

inputs:
  push:
    required: false
    default: false
  load:
    required: false
    default: false
  tags:
    required: false
    default: ""
    description: "additional tags"

  token:
    required: true
    description: "Github-Token"

outputs:
  docker-image-tag:
    value: ${{ steps.meta.outputs.tags }}
    description: "docker tag"




runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@3d100841f68d4548bf57e52eb27bd33ec5069f55
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@de1119515dcfb4b110f21f67dc739b3ba1472a84
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          ${{ inputs.tags }}
          type=ref,event=branch
          type=sha

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      with:
        context: .
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: actionfiles/aquafier-ts/dockerfile/Dockerfile