name: build_container
author: itstimetoforget
description: build_container

inputs:
  push:
    required: false
    default: false
  load:
    required: false
    default: false

  token:
    required: true
    description: "Github-Token"

outputs:
  docker-image-tag:
    value: ${{ steps.meta.outputs.tags }}
    description: "docker tag"




runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: actionfiles/aquafier-ts/dockerfile/Dockerfile