name: "Build Docker-Container"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
      - dev
      - playwright

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        uses: ./.github/actions/build_container
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push: true

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: build
    uses: ./.github/workflows/deploy-dev.yml
    secrets:
      RUNNER_PRIVATE_KEY: ${{ secrets.RUNNER_PRIVATE_KEY }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: build
    uses: ./.github/workflows/deploy-main.yml
    secrets:
      RUNNER_PRIVATE_KEY: ${{ secrets.RUNNER_PRIVATE_KEY }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
