name: "Build Docker-Container"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch:
    
  # push:
  #   branches:
  #     - main
  #     - dev
  #     - playwright
  #     - add-additional-tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set build info
        shell: bash
        run: |
          echo "{ \
          \"commitHash\": \"$(git rev-parse --short HEAD)\", \
           \"buildDate\": \"$(git log -1 --format='%cd' --date=local)\" \
           }" > ./web/src/version-info.json
      - name: build
        uses: ./.github/actions/build_container
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push: true

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: build
    uses: ./.github/workflows/deploy-dev.yml
    secrets:
      RUNNER_PRIVATE_KEY: ${{ secrets.RUNNER_PRIVATE_KEY }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: build
    uses: ./.github/workflows/deploy-main.yml
    secrets:
      RUNNER_PRIVATE_KEY: ${{ secrets.RUNNER_PRIVATE_KEY }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
