name: "Deploy Dev-Environment"

on:
  workflow_call:
    secrets:
      RUNNER_PRIVATE_KEY:
        required: true
      PRIVATE_KEY_PASSWORD:
        required: true
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute update on host
        uses: appleboy/ssh-action@v1
        with:
          host: "aquafier.inblock.io"
          username: "sammy"
          key: ${{ secrets.RUNNER_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          script: /home/sammy/scripts/pull_latest_version_aquafier-js.sh